version: "3"
services:
  env:
    build:
      context: sim_SUAS
      dockerfile: Env.Containerfile
    container_name: multirotor_env
    network_mode: host
    volumes:
      - type: bind
        source: ./
        target: /sim_SUAS
    working_dir: /SUAS
    command: bash
    stdin_open: true
    tty: true
  sim:
    build:
      context: sim_SUAS
      dockerfile: Sim.Containerfile
    container_name: multirotor_sim
    network_mode: host
    command: python /ardupilot/Tools/autotest/sim_vehicle.py -v ArduCopter -f airsim-copter --out=127.0.0.1:14550
    stdin_open: true
    tty: true