version: "3"
services:
  env:
    build:
      context: ..
      dockerfile: simulation/Env.Containerfile
    container_name: multirotor_env
    network_mode: host
    volumes:
      - type: bind
        source: ..
        target: /SUAS
    working_dir: /SUAS
    command: bash
    stdin_open: true
    tty: true
  sim:
    environment:  # See Sim.Containerfile for explanations
      - OUT_PORT=14550
      - OUT_HOST=127.0.0.1
      - NUM_DRONES=1
    build:
      context: ..
      dockerfile: simulation/Sim.Containerfile
    container_name: multirotor_sim
    network_mode: host
<<<<<<< HEAD
    # command: python /ardupilot/Tools/autotest/sim_vehicle.py -v ArduCopter -f airsim-copter --out=udp:host.docker.internal:9003
    command: python /ardupilot/Tools/autotest/sim_vehicle.py -v ArduCopter -f airsim-copter --out=127.0.0.1:14550 -A "--sim-port-in=9002 --sim-port-out=9003"
=======
>>>>>>> feature/projectairsim-multidrone
    stdin_open: true
    tty: true
    command: /ardupilot/Tools/autotest/sim_start_drones.sh ${NUM_DRONES} ${OUT_PORT} ${OUT_HOST}
